mybatis-plus:
  configuration:
  #默认为true 下划线转驼峰，如果改成false 发送的sql语句就为 驼峰命名的
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      #取消下划线
      table-underline: true
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
   com.chao.ssmvue: debug
server:
  port: 8082




